Allow running in Docker on Windows
NUbots/NUsight2 pull request #335
Opened 2020-11-18 06:16 UTC by JosephusPaye

Pairs with https://github.com/NUbots/NUbots/pull/341.

This adds a simple docker-compose file for running NUsight in a docker container to get it to talk to NUbots in a container on Windows.

Using `docker-compose` (instead of just `docker`) allows for creating the container on demand without a Dockerfile + `docker build`.

It also adds a shell script to make it easier to run the docker-compose commands. I considered adding the commands as scripts to `package.json`, but `yarn` reports two spurious errors on SIGINT exit.

---

To be used as follows (proper NUbook documentation coming soon), all commands run in WSL on Windows:

### Setup

- Create the network: `docker network create nuclearnet`
- Make the docker script executable: `chmod +x ./docker`

### Build

- Install NUsight deps in the container `./docker yarn`
- Build NUsight for prod in the container `./docker yarn build`

### Run

- Run something in NUbots and connect it to the network: `./b run keyboardwalkfake --network nuclearnet`
- Inspect the network to find the NUbots container's IP address, X: `docker network inspect nuclearnet`
- Run NUsight with the NUbots container address: `./docker yarn prod --address X`

2020-11-18 10:28 UTC, ysims approved these changes
I've tested this and it all works. Script looks fine.

2020-11-18 12:22 UTC, BrendanAnnable reviewed
LGTM if LGTTrent, can we add documentation somewhere?

2020-11-18 22:40 UTC, TrentHouliston requested changes
A few comments based on when I did this before.
I would recommend mounting a volume over the node_modules folder so you can have both the local and docker versions still work.
Commit a .gitignore file in the node_modules folder to keep it anchored.

Also I would recommend rather than having to run a script to find the address of the nubots system, just using the multicasting or broadcasting that is built into NUClear as it works just fine over the docker network

2020-11-23 09:38 UTC, JosephusPaye commented
It currently mounts the entire NUsight2 folder, including `node_modules` in the container.

How do we use the multicasting/broadcasting?

2020-11-23 12:48 UTC, TrentHouliston commented
> It currently mounts the entire NUsight2 folder, including `node_modules` in the container.

You need to overmount a new volume over the `node_modules` folder that way the host has a different copy of the files

> How do we use the multicasting/broadcasting?

You'll have to test it but I'm pretty sure that just using the default multicast address that NUsight2 defaults to should work.
Within the docker network, it should sort itself out without you having to set anything special.
Really it should work on the normal robots too.

2020-11-24 02:09 UTC, JosephusPaye commented
Is there something we need to do on the NUsight side for multicasting?

I just tried and it doesn't work without an explicit `--address`. Probably because it tries to connect to the default `10.1.255.255` that we use in the lab?

2020-11-25 02:56 UTC, JosephusPaye commented
Documented in NUbook: https://nubook.netlify.app/guides/main/getting-started#get-build-and-run-nusight

2020-11-25 02:57 UTC, TrentHouliston approved these changes
@JosephusPaye promised that he would make more PRs to fix the multicast addressing!

2020-11-25 02:59 UTC, merged